---
volumes:
  etc_pihole-unbound:
  etc_pihole_dnsmasq-unbound:

networks:
    edge:
      external: true

services:
  pihole:
    # dns:
    #   - 127.0.0.1
    container_name: pihole
    build:
      context: .
      dockerfile: Dockerfile
    image: aleksanderbl/pihole-unbound:latest
    hostname: ${HOSTNAME}
    #domainname: ${DOMAIN_NAME}
    ports:
      #- 443:443/tcp #Not needed
      - 53:53/tcp
      - 53:53/udp
      - ${PIHOLE_WEBPORT:-80}:80/tcp #Allows use of different port to access pihole web interface when other docker containers use port 80
      # - 5335:5335/tcp # Uncomment to enable unbound access on local server
      # - 22/tcp # Uncomment to enable SSH
    environment:
      - TZ=${TZ:-UTC}
      - FTLCONF_webserver_api_password=${WEBPASSWORD}
      - FTLCONF_webserver_interface_theme=${WEBTHEME:-default-dark}
      - FTLCONF_dns_upstreams=127.0.0.1#5335
      - FTLCONF_dns_dnssec="true"
      - FTLCONF_dns_listeningMode=single
      - BLOCKLISTS_URL='https://v.firebog.net/hosts/lists.php?type=tick'
      - REGEX_BLACKLIST_URL='https://raw.githubusercontent.com/mmotti/pihole-regex/master/regex.list'
    volumes:
      - etc_pihole-unbound:/etc/pihole:rw
      - etc_pihole_dnsmasq-unbound:/etc/dnsmasq.d:rw
    networks: 
      - edge
    restart: unless-stopped


